# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "HelloWorld"
  HelloWorld:
    strategy:
      matrix:
        node-version: [16.11.1]
    runs-on: ubuntu-latest
    # The type of runner that the job will run on
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo 'Working in Ubuntu'
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Nodejs
        run: actions/setup-node@v2

      - run: echo 'Nodejs already'

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: node demo.js
